type: app
description: Default stackfile usecase create hybrid apps with React Native and Expo CLI
# template used to create the project
template: expo-react-native/new-project
inputs:
  package_name: text
# list of plugins to be applied after project creation
plugins:
  - plugin: expo-react-native/<plugin-name>
    inputs:
      some_input: value
      some_list:
        - item1
        - item2
