name: firebase-plugin
description: Inclusão do Firebase no projeto React Native
display-name: Firebase
picture: plugin.png
category: frontend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility:
  - react native
  - typescript
  - javascript
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies
  - "JavaScript"
  - "React"
  - "Typescript"
types:
  - app
inputs:
  - label: Selecione os pacotes a serem instalados
    type: multiselect
    name: fire_packages
    items:
      - "Analytics"
      - "Authentication"
      - "Cloud Firestore"
      - "Crashlytics"

computed-inputs:
  analytics: "{% if 'Analytics' in inputs.fire_packages %}{{yarn add @react-native-firebase/analytics}}{% else %}{{echo sem analytics}}{% endif %}"

hooks:
  - type: run
    trigger: before-render
    commands:
      - yarn add @react-native-firebase/app
      - {{computed-input.analytics}}
      # - cd ios && pod install
  # - type: edit
  #   trigger: before-render
  #   path: "/ios/{{computed_inputs.appname}}/AppDelegate.mm"
  #   changes:
  #     - search:
  #       string: '#import "AppDelegate.h"'
  #       insert-before:
  #         value: "#import <Firebase.h>"
